[colors.bright]
black = "0x3c3836"
blue = "0x7daea3"
cyan = "0x89b482"
green = "0xa9b665"
magenta = "0xd3869b"
red = "0xea6962"
white = "0xd4be98"
yellow = "0xd8a657"

[colors.normal]
black = "0x3c3836"
blue = "0x7daea3"
cyan = "0x89b482"
green = "0xa9b665"
magenta = "0xd3869b"
red = "0xea6962"
white = "0xd4be98"
yellow = "0xd8a657"

[colors.primary]
background = "0x000000"
foreground = "0xd4be98"

[font]
size = 11

[font.bold]
family = "Hack Nerd Font"

[font.italic]
family = "Hack Nerd Font"

[font.normal]
family = "Hack Nerd Font"

[schemes.gruvbox_material_hard_dark.bright]
black = "0x32302f"
blue = "0x7daea3"
cyan = "0x89b482"
green = "0xa9b665"
magenta = "0xd3869b"
red = "0xea6962"
white = "0xd4be98"
yellow = "0xd8a657"

[schemes.gruvbox_material_hard_dark.normal]
black = "0x32302f"
blue = "0x7daea3"
cyan = "0x89b482"
green = "0xa9b665"
magenta = "0xd3869b"
red = "0xea6962"
white = "0xd4be98"
yellow = "0xd8a657"

[schemes.gruvbox_material_hard_dark.primary]
background = "0x1d2021"
foreground = "0xd4be98"

[schemes.gruvbox_material_hard_light.bright]
black = "0x654735"
blue = "0x45707a"
cyan = "0x4c7a5d"
green = "0x6c782e"
magenta = "0x945e80"
red = "0xc14a4a"
white = "0xf2e5bc"
yellow = "0xb47109"

[schemes.gruvbox_material_hard_light.normal]
black = "0x654735"
blue = "0x45707a"
cyan = "0x4c7a5d"
green = "0x6c782e"
magenta = "0x945e80"
red = "0xc14a4a"
white = "0xf2e5bc"
yellow = "0xb47109"

[schemes.gruvbox_material_hard_light.primary]
background = "0xf9f5d7"
foreground = "0x654735"

[schemes.gruvbox_material_medium_dark.bright]
black = "0x3c3836"
blue = "0x7daea3"
cyan = "0x89b482"
green = "0xa9b665"
magenta = "0xd3869b"
red = "0xea6962"
white = "0xd4be98"
yellow = "0xd8a657"

[schemes.gruvbox_material_medium_dark.normal]
black = "0x3c3836"
blue = "0x7daea3"
cyan = "0x89b482"
green = "0xa9b665"
magenta = "0xd3869b"
red = "0xea6962"
white = "0xd4be98"
yellow = "0xd8a657"

[schemes.gruvbox_material_medium_dark.primary]
background = "0x282828"
foreground = "0xd4be98"

[schemes.gruvbox_material_medium_light.bright]
black = "0x654735"
blue = "0x45707a"
cyan = "0x4c7a5d"
green = "0x6c782e"
magenta = "0x945e80"
red = "0xc14a4a"
white = "0xeee0b7"
yellow = "0xb47109"

[schemes.gruvbox_material_medium_light.normal]
black = "0x654735"
blue = "0x45707a"
cyan = "0x4c7a5d"
green = "0x6c782e"
magenta = "0x945e80"
red = "0xc14a4a"
white = "0xeee0b7"
yellow = "0xb47109"

[schemes.gruvbox_material_medium_light.primary]
background = "0xfbf1c7"
foreground = "0x654735"

[schemes.gruvbox_material_soft_dark.bright]
black = "0x45403d"
blue = "0x7daea3"
cyan = "0x89b482"
green = "0xa9b665"
magenta = "0xd3869b"
red = "0xea6962"
white = "0xd4be98"
yellow = "0xd8a657"

[schemes.gruvbox_material_soft_dark.normal]
black = "0x45403d"
blue = "0x7daea3"
cyan = "0x89b482"
green = "0xa9b665"
magenta = "0xd3869b"
red = "0xea6962"
white = "0xd4be98"
yellow = "0xd8a657"

[schemes.gruvbox_material_soft_dark.primary]
background = "0x32302f"
foreground = "0xd4be98"

[schemes.gruvbox_material_soft_light.bright]
black = "0x654735"
blue = "0x45707a"
cyan = "0x4c7a5d"
green = "0x6c782e"
magenta = "0x945e80"
red = "0xc14a4a"
white = "0xe6d5ae"
yellow = "0xb47109"

[schemes.gruvbox_material_soft_light.normal]
black = "0x654735"
blue = "0x45707a"
cyan = "0x4c7a5d"
green = "0x6c782e"
magenta = "0x945e80"
red = "0xc14a4a"
white = "0xe6d5ae"
yellow = "0xb47109"

[schemes.gruvbox_material_soft_light.primary]
background = "0xf2e5bc"
foreground = "0x654735"

[schemes.nightfly]
draw_bold_text_with_bright_colors = true

[schemes.nightfly.bright]
black = "#7c8f8f"
blue = "#82aaff"
cyan = "#7fdbca"
green = "#21c7a8"
magenta = "#ae81ff"
red = "#ff5874"
white = "#d6deeb"
yellow = "#ecc48d"

[schemes.nightfly.cursor]
cursor = "#9ca1aa"
text = "#080808"

[schemes.nightfly.normal]
black = "#1d3b53"
blue = "#82aaff"
cyan = "#7fdbca"
green = "#a1cd5e"
magenta = "#c792ea"
red = "#fc514e"
white = "#a1aab8"
yellow = "#e3d18a"

[schemes.nightfly.primary]
background = "#131418"
bright_foreground = "#eeeeee"
foreground = "#acb4c2"

[schemes.nightfly.selection]
background = "#b2ceee"
text = "#080808"

[schemes.one_darker.bright]
black = "#4C566A"
blue = "#5e81ac"
cyan = "#88c0d0"
green = "#A3BE8C"
magenta = "#B48EAD"
red = "#bf616a"
white = "#abb2bf"
yellow = "#D7BA7D"

[schemes.one_darker.normal]
black = "#4C566A"
blue = "#5e81ac"
cyan = "#88c0d0"
green = "#A3BE8C"
magenta = "#B48EAD"
red = "#bf616a"
white = "#abb2bf"
yellow = "#D7BA7D"

[schemes.one_darker.primary]
background = "#1f2227"
foreground = "#abb2bf"

[schemes.tokyo-night.bright]
black = "#444b6a"
blue = "#7da6ff"
cyan = "#0db9d7"
green = "#b9f27c"
magenta = "#bb9af7"
red = "#ff7a93"
white = "#acb0d0"
yellow = "#ff9e64"

[schemes.tokyo-night.normal]
black = "#32344a"
blue = "#7aa2f7"
cyan = "#449dab"
green = "#9ece6a"
magenta = "#ad8ee6"
red = "#f7768e"
white = "#787c99"
yellow = "#e0af68"

[schemes.tokyo-night.primary]
background = "#1a1b26"
foreground = "#a9b1d6"

[schemes.tokyo-night-storm.bright]
black = "#444b6a"
blue = "#7da6ff"
cyan = "#0db9d7"
green = "#b9f27c"
magenta = "#bb9af7"
red = "#ff7a93"
white = "#acb0d0"
yellow = "#ff9e64"

[schemes.tokyo-night-storm.normal]
black = "#32344a"
blue = "#7aa2f7"
cyan = "#449dab"
green = "#9ece6a"
magenta = "#ad8ee6"
red = "#f7768e"
white = "#9699a8"
yellow = "#e0af68"

[schemes.tokyo-night-storm.primary]
background = "#24283b"
foreground = "#a9b1d6"

[window]
opacity = 1

[window.padding]
x = 10
y = 10
